# Generated by Django 3.1.5 on 2021-04-04 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mysite.core.models.basic_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=2000)),
                ('expiration', models.DateField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('domainExamination', models.BooleanField(verbose_name='examination domain')),
                ('domainProduct', models.BooleanField(verbose_name='product domain')),
                ('domainPerformance', models.BooleanField(verbose_name='performance domain')),
                ('directMeasure', models.BooleanField(verbose_name='direct measure')),
                ('numberOfUses', models.PositiveIntegerField(default=0, verbose_name='number of uses')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('GR', 'Graduate')], max_length=75)),
                ('cycle', models.IntegerField(blank=True, null=True)),
                ('startingYear', models.PositiveIntegerField(blank=True, null=True, verbose_name='starting year of cycle')),
                ('active', models.BooleanField(default=True)),
                ('accredited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=mysite.core.models.basic_models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='GradGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=600)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('accredited', models.BooleanField(default=False)),
                ('date_range_of_reported_data', models.CharField(blank=True, max_length=500, null=True)),
                ('section1Comment', models.CharField(blank=True, max_length=2000, null=True, verbose_name='section I comment')),
                ('section2Comment', models.CharField(blank=True, max_length=2000, null=True, verbose_name='section II comment')),
                ('section3Comment', models.CharField(blank=True, max_length=2000, null=True, verbose_name='section III comment')),
                ('section4Comment', models.CharField(blank=True, max_length=2000, null=True, verbose_name='section IV comment')),
                ('submitted', models.BooleanField()),
                ('returned', models.BooleanField(default=False)),
                ('numberOfSLOs', models.PositiveIntegerField(default=0, verbose_name='number of SLOs')),
                ('title', models.CharField(max_length=100)),
                ('uploader', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='reports/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='reports/covers/')),
                ('degreeProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.degreeprogram', verbose_name='degree program')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredFieldSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Setting', max_length=200)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SLO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blooms', models.CharField(choices=[('', '------'), ('KN', 'Knowledge'), ('CO', 'Comprehension'), ('AP', 'Application'), ('AN', 'Analysis'), ('SN', 'Synthesis'), ('EV', 'Evaluation')], max_length=50, verbose_name="Bloom's taxonomy level")),
                ('numberOfUses', models.PositiveIntegerField(default=0, verbose_name='number of uses of this SLO')),
                ('gradGoals', models.ManyToManyField(to='core.GradGoal', verbose_name='graduate-level goals')),
            ],
        ),
        migrations.CreateModel(
            name='SLOInReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goalText', models.CharField(max_length=1000, verbose_name='goal text')),
                ('changedFromPrior', models.BooleanField(verbose_name='changed from prior version')),
                ('number', models.PositiveIntegerField(default=1)),
                ('numberOfAssess', models.PositiveIntegerField(default=0, verbose_name='number of assessments')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.report')),
                ('slo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.slo', verbose_name='SLO')),
            ],
        ),
        migrations.CreateModel(
            name='SLOsToStakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.report')),
            ],
        ),
        migrations.CreateModel(
            name='SLOStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Met', 'Met'), ('Partially Met', 'Partially Met'), ('Not Met', 'Not Met'), ('Unknown', 'Unknown')], max_length=50)),
                ('override', models.BooleanField(default=False)),
                ('sloIR', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.sloinreport')),
            ],
        ),
        migrations.CreateModel(
            name='ResultCommunicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.report')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aac', models.BooleanField(null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='degreeprogram',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.CreateModel(
            name='DecisionsActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=3000)),
                ('sloIR', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.sloinreport')),
            ],
        ),
        migrations.CreateModel(
            name='DataAdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=3000)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.report')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('changedFromPrior', models.BooleanField(verbose_name='changed from prior version')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('finalTerm', models.BooleanField(verbose_name='final term')),
                ('where', models.CharField(max_length=500, verbose_name='location of assessment')),
                ('allStudents', models.BooleanField(verbose_name='all students assessed')),
                ('sampleDescription', models.CharField(blank=True, max_length=500, null=True, verbose_name='description of sample')),
                ('frequencyChoice', models.CharField(choices=[('S', 'Once/semester'), ('Y', 'Once/year'), ('O', 'Other')], default='O', max_length=100, verbose_name='frequency choice')),
                ('frequency', models.CharField(max_length=500)),
                ('threshold', models.CharField(max_length=500)),
                ('target', models.PositiveIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assessment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.report')),
                ('slo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sloinreport', verbose_name='SLO in report')),
                ('supplements', models.ManyToManyField(to='core.AssessmentSupplement')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRange', models.CharField(max_length=500, verbose_name='data range')),
                ('numberStudents', models.PositiveIntegerField(verbose_name='number of students')),
                ('overallProficient', models.PositiveIntegerField(blank=True, verbose_name='overall percentage proficient')),
                ('assessmentVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assessmentversion', verbose_name='assessment version')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_proficiency', models.PositiveIntegerField(verbose_name='aggregate proficiency percentage')),
                ('met', models.BooleanField(verbose_name='target met')),
                ('override', models.BooleanField(default=False)),
                ('assessmentVersion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.assessmentversion', verbose_name='assessment version')),
            ],
        ),
    ]
