# Generated by Django 2.1.3 on 2021-04-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
