# Generated by Django 3.1.5 on 2021-04-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210421_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sloinreport',
            name='date',
        ),
    ]
