# Generated by Django 3.1.5 on 2021-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210410_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('uploader', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='reports/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='reports/covers/')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pdf',
        ),
    ]
