# Generated by Django 3.1.5 on 2021-04-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sloinreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='degreeProgram',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
