.TH "mysite/core/models/basic_models.py" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/core/models/basic_models.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmysite\&.core\&.models\&.basic_models\&.NonArchivedManager\fP"
.br
.ti -1c
.RI "class \fBmysite\&.core\&.models\&.basic_models\&.UploadReport\fP"
.br
.ti -1c
.RI "class \fBmysite\&.core\&.models\&.basic_models\&.Report\fP"
.br
.ti -1c
.RI "class \fBmysite\&.core\&.models\&.basic_models\&.Profile\fP"
.br
.ti -1c
.RI "class \fBmysite\&.core\&.models\&.basic_models\&.FileModel\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmysite\&.core\&.models\&.basic_models\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmysite\&.core\&.models\&.basic_models\&.user_directory_path\fP (instance, filename)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
