.TH "mysite/core Directory Reference" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmigrations\fP"
.br
.ti -1c
.RI "directory \fBmodels\fP"
.br
.ti -1c
.RI "directory \fBpaser\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBadmin\&.py\fP"
.br
.ti -1c
.RI "file \fBapps\&.py\fP"
.br
.ti -1c
.RI "file \fBchoices\&.py\fP"
.br
.ti -1c
.RI "file \fBforms\&.py\fP"
.br
.ti -1c
.RI "file \fBtests\&.py\fP"
.br
.ti -1c
.RI "file \fBviews\&.py\fP"
.br
.in -1c
