.TH "mysite/core/paser Directory Reference" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/core/paser Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinsertData\&.py\fP"
.br
.ti -1c
.RI "file \fBmain_parser\&.py\fP"
.br
.ti -1c
.RI "file \fBmain_parserv2\&.py\fP"
.br
.ti -1c
.RI "file \fBos_manip\&.py\fP"
.br
.ti -1c
.RI "file \fBread_doc_chx\&.py\fP"
.br
.ti -1c
.RI "file \fBread_doc_test\&.py\fP"
.br
.in -1c
