.TH "mysite/core/migrations Directory Reference" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/core/migrations Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB0001_initial\&.py\fP"
.br
.ti -1c
.RI "file \fB0002_auto_20210421_1533\&.py\fP"
.br
.ti -1c
.RI "file \fB0003_remove_sloinreport_date\&.py\fP"
.br
.ti -1c
.RI "file \fB0004_auto_20210428_1546\&.py\fP"
.br
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.in -1c
