.TH "mysite/core/choices.py" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/core/choices.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmysite\&.core\&.choices\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBmysite\&.core\&.choices\&.BLOOMS_CHOICES\fP"
.br
.ti -1c
.RI "tuple \fBmysite\&.core\&.choices\&.RUBRIC_GRADES_CHOICES\fP"
.br
.ti -1c
.RI "tuple \fBmysite\&.core\&.choices\&.LEVELS\fP"
.br
.ti -1c
.RI "tuple \fBmysite\&.core\&.choices\&.SECTIONS\fP"
.br
.ti -1c
.RI "tuple \fBmysite\&.core\&.choices\&.DOMAIN_CHOICES\fP"
.br
.ti -1c
.RI "tuple \fBmysite\&.core\&.choices\&.SLO_STATUS_CHOICES\fP"
.br
.ti -1c
.RI "tuple \fBmysite\&.core\&.choices\&.FREQUENCY_CHOICES\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
