.TH "insertData" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
insertData
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBinsertCheckBox\fP (list_of_lists)"
.br
.ti -1c
.RI "def \fBinsertReportHeader\fP (match_list, list_of_lists, accredited1, length_slo, dec_act, assessment_methods, slo_list, data_coll_list)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def insertData\&.insertCheckBox ( list_of_lists)"

.SS "def insertData\&.insertReportHeader ( match_list,  list_of_lists,  accredited1,  length_slo,  dec_act,  assessment_methods,  slo_list,  data_coll_list)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
