.TH "mysite/core/paser/insertData.py" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/core/paser/insertData.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBinsertData\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBinsertData\&.insertCheckBox\fP (list_of_lists)"
.br
.ti -1c
.RI "def \fBinsertData\&.insertReportHeader\fP (match_list, list_of_lists, accredited1, length_slo, dec_act, assessment_methods, slo_list, data_coll_list)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
