.TH "mysite/core/paser/main_parser.py" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/core/paser/main_parser.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmain_parser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain_parser\&.assessmentMethodProcessor\fP (assessment_methods)"
.br
.ti -1c
.RI "def \fBmain_parser\&.regex_inc\fP (regex, match_list, header_text)"
.br
.RI "Applies a regular expression to a block of text\&. "
.ti -1c
.RI "def \fBmain_parser\&.table_two_access\fP (is_accredited, column, table, row_iter, data, one_cols, max_rows)"
.br
.RI "Captures the information in the Assessment Methods table(s) of the document\&. "
.ti -1c
.RI "def \fBmain_parser\&.grad_unaccredited_assessment\fP (column, report_year, doc, slo_count, data, one_cols, max_rows)"
.br
.RI "Captures the information in Non-Accredited Graduate reports in the Assessment Methods table(s) of the document\&. "
.ti -1c
.RI "def \fBmain_parser\&.table_three_access\fP (column, table, row_iter, data, one_cols, max_rows, slo_count)"
.br
.RI "Captures the information in the Data (Collection &) Analysis table of the document\&. "
.ti -1c
.RI "def \fBmain_parser\&.table_four_access\fP (is_accredited, column, table, row_iter, data_coll_list, slo_count)"
.br
.RI "Captures the information in the Decisions & Actions table of the document\&. "
.ti -1c
.RI "def \fBmain_parser\&.run\fP (uploaded_filename)"
.br
.RI "This function captures the information from documents\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
