.TH "main.Program_test_case" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.Program_test_case
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtest_title\fP (self)"
.br
.ti -1c
.RI "def \fBtest_main_page\fP (self)"
.br
.ti -1c
.RI "def \fBtest_click_simple_upload\fP (self)"
.br
.ti -1c
.RI "def \fBtest_file_upload_submit_without_files\fP (self)"
.br
.ti -1c
.RI "def \fBtest_file_upload_submit_with_files\fP (self)"
.br
.ti -1c
.RI "def \fBtest_file_upload_submit_with_files2\fP (self)"
.br
.ti -1c
.RI "def \fBtest_delete_reports_page\fP (self)"
.br
.ti -1c
.RI "def \fBtest_delete_reports_page_delete_buttom\fP (self)"
.br
.ti -1c
.RI "def \fBtest_search_page\fP (self)"
.br
.ti -1c
.RI "def \fBtest_report_show_page\fP (self)"
.br
.ti -1c
.RI "def \fBtearDown\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdriver\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def main\&.Program_test_case\&.setUp ( self)"

.SS "def main\&.Program_test_case\&.tearDown ( self)"

.SS "def main\&.Program_test_case\&.test_click_simple_upload ( self)"

.SS "def main\&.Program_test_case\&.test_delete_reports_page ( self)"

.SS "def main\&.Program_test_case\&.test_delete_reports_page_delete_buttom ( self)"

.SS "def main\&.Program_test_case\&.test_file_upload_submit_with_files ( self)"

.SS "def main\&.Program_test_case\&.test_file_upload_submit_with_files2 ( self)"

.SS "def main\&.Program_test_case\&.test_file_upload_submit_without_files ( self)"

.SS "def main\&.Program_test_case\&.test_main_page ( self)"

.SS "def main\&.Program_test_case\&.test_report_show_page ( self)"

.SS "def main\&.Program_test_case\&.test_search_page ( self)"

.SS "def main\&.Program_test_case\&.test_title ( self)"

.SH "Member Data Documentation"
.PP 
.SS "main\&.Program_test_case\&.driver"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
