.TH "mysite/core/paser/main_parserv2.py" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/core/paser/main_parserv2.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmain_parserv2\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain_parserv2\&.assessmentMethodProcessor\fP (assessment_methods)"
.br
.ti -1c
.RI "def \fBmain_parserv2\&.regex_inc\fP (regex_list, regex_counter, match_list, para)"
.br
.RI "Allows a for loop to loop through a list of regular expressions\&. "
.ti -1c
.RI "def \fBmain_parserv2\&.table_two_access\fP (is_accredited, column, table, row_iter, data, one_cols, max_rows)"
.br
.RI "Captures the information in the Assessment Methods table(s) of the document\&. "
.ti -1c
.RI "def \fBmain_parserv2\&.table_three_access\fP (column, table, row_iter, data, one_cols, max_rows, slo_count)"
.br
.RI "Captures the information in the Data (Collection &) Analysis table of the document\&. "
.ti -1c
.RI "def \fBmain_parserv2\&.table_four_access\fP (is_accredited, column, table, row_iter, data_coll_list, slo_count)"
.br
.RI "Captures the information in the Decisions & Actions table of the document\&. "
.ti -1c
.RI "def \fBmain_parserv2\&.run\fP (uploaded_filename)"
.br
.RI "This function captures the information from documents\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
