.TH "mysite.core.models.aac_models.RequiredFieldSetting" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.aac_models.RequiredFieldSetting
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP = models\&.CharField(max_length=200, blank=True, default='Setting')"
.br
.ti -1c
.RI "\fBrequired\fP = models\&.BooleanField(default=False)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Model to hold settings for required field to submit report

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "mysite\&.core\&.models\&.aac_models\&.RequiredFieldSetting\&.name = models\&.CharField(max_length=200, blank=True, default='Setting')\fC [static]\fP"

.SS "mysite\&.core\&.models\&.aac_models\&.RequiredFieldSetting\&.required = models\&.BooleanField(default=False)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
