.TH "mysite.core.views.ReportListView" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.views.ReportListView
.SH SYNOPSIS
.br
.PP
.PP
Inherits ListView\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBmodel\fP = \fBReport\fP"
.br
.ti -1c
.RI "string \fBtemplate_name\fP = 'class_report_list\&.html'"
.br
.ti -1c
.RI "string \fBcontext_object_name\fP = 'reports'"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string mysite\&.core\&.views\&.ReportListView\&.context_object_name = 'reports'\fC [static]\fP"

.SS "mysite\&.core\&.views\&.ReportListView\&.model = \fBReport\fP\fC [static]\fP"

.SS "string mysite\&.core\&.views\&.ReportListView\&.template_name = 'class_report_list\&.html'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
