.TH "mysite.core.views.UploadReportView" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.views.UploadReportView
.SH SYNOPSIS
.br
.PP
.PP
Inherits CreateView\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBmodel\fP = \fBReport\fP"
.br
.ti -1c
.RI "\fBform_class\fP = \fBReportForm\fP"
.br
.ti -1c
.RI "\fBsuccess_url\fP = reverse_lazy('class_report_list')"
.br
.ti -1c
.RI "string \fBtemplate_name\fP = 'upload_report\&.html'"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "mysite\&.core\&.views\&.UploadReportView\&.form_class = \fBReportForm\fP\fC [static]\fP"

.SS "mysite\&.core\&.views\&.UploadReportView\&.model = \fBReport\fP\fC [static]\fP"

.SS "mysite\&.core\&.views\&.UploadReportView\&.success_url = reverse_lazy('class_report_list')\fC [static]\fP"

.SS "string mysite\&.core\&.views\&.UploadReportView\&.template_name = 'upload_report\&.html'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
