.TH "mysite.core.models.aac_models" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.aac_models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCollege\fP"
.br
.ti -1c
.RI "class \fBDepartment\fP"
.br
.ti -1c
.RI "class \fBDegreeProgram\fP"
.br
.ti -1c
.RI "class \fBAnnouncement\fP"
.br
.ti -1c
.RI "class \fBRequiredFieldSetting\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Includes models principally managed by the AAC, which act both as Python objects and abstractions for database items
Copied from previous project

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
