.TH "mysite.core.models.basic_models.FileModel" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.basic_models.FileModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBtitle\fP = models\&.CharField(max_length=50)"
.br
.ti -1c
.RI "\fBfile\fP = models\&.FileField(upload_to=\fBuser_directory_path\fP)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "mysite\&.core\&.models\&.basic_models\&.FileModel\&.file = models\&.FileField(upload_to=\fBuser_directory_path\fP)\fC [static]\fP"

.SS "mysite\&.core\&.models\&.basic_models\&.FileModel\&.title = models\&.CharField(max_length=50)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
