.TH "mysite.core.forms.ReportForm.Meta" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.forms.ReportForm.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBmodel\fP = \fBUploadReport\fP"
.br
.ti -1c
.RI "tuple \fBfields\fP = ('title', 'uploader', 'pdf', 'cover')"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "tuple mysite\&.core\&.forms\&.ReportForm\&.Meta\&.fields = ('title', 'uploader', 'pdf', 'cover')\fC [static]\fP"

.SS "mysite\&.core\&.forms\&.ReportForm\&.Meta\&.model = \fBUploadReport\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
