.TH "mysite.core.models.slo_models.SLOsToStakeholder" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.slo_models.SLOsToStakeholder
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBtext\fP = models\&.CharField(max_length=2000)"
.br
.ti -1c
.RI "\fBreport\fP = models\&.ForeignKey('\fBReport\fP', on_delete=models\&.CASCADE, null=True)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Text describing how SLOs are communicated to stakeholders

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def mysite\&.core\&.models\&.slo_models\&.SLOsToStakeholder\&.__str__ ( self)"

.SH "Member Data Documentation"
.PP 
.SS "mysite\&.core\&.models\&.slo_models\&.SLOsToStakeholder\&.report = models\&.ForeignKey('\fBReport\fP', on_delete=models\&.CASCADE, null=True)\fC [static]\fP"

.SS "mysite\&.core\&.models\&.slo_models\&.SLOsToStakeholder\&.text = models\&.CharField(max_length=2000)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
