.TH "mysite.core.models.slo_models.GradGoal" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.slo_models.GradGoal
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBtext\fP = models\&.CharField(max_length=600)"
.br
.ti -1c
.RI "\fBactive\fP = models\&.BooleanField(default=True)"
.br
.ti -1c
.RI "\fBobjects\fP = models\&.Manager()"
.br
.ti -1c
.RI "\fBactive_objects\fP = \fBNonArchivedManager\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A graduate goal graduate level programs may obtain

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def mysite\&.core\&.models\&.slo_models\&.GradGoal\&.__str__ ( self)"

.SH "Member Data Documentation"
.PP 
.SS "mysite\&.core\&.models\&.slo_models\&.GradGoal\&.active = models\&.BooleanField(default=True)\fC [static]\fP"

.SS "mysite\&.core\&.models\&.slo_models\&.GradGoal\&.active_objects = \fBNonArchivedManager\fP()\fC [static]\fP"

.SS "mysite\&.core\&.models\&.slo_models\&.GradGoal\&.objects = models\&.Manager()\fC [static]\fP"

.SS "mysite\&.core\&.models\&.slo_models\&.GradGoal\&.text = models\&.CharField(max_length=600)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
