.TH "mysite.core.models.data_models.ResultCommunicate" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.data_models.ResultCommunicate
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBtext\fP = models\&.CharField(max_length=3000)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Model holds the text for communicating results

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "mysite\&.core\&.models\&.data_models\&.ResultCommunicate\&.text = models\&.CharField(max_length=3000)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
