.TH "mysite.core.models.assessment_models.AssessmentSupplement" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.assessment_models.AssessmentSupplement
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Supplemental files to assessments
Removed for this project

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
