.TH "mysite.core.views.Home" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.views.Home
.SH SYNOPSIS
.br
.PP
.PP
Inherits TemplateView\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBtemplate_name\fP = 'home\&.html'"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string mysite\&.core\&.views\&.Home\&.template_name = 'home\&.html'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
