.TH "mysite.core.models.assessment_models" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.assessment_models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssessment\fP"
.br
.ti -1c
.RI "class \fBAssessmentVersion\fP"
.br
.ti -1c
.RI "class \fBAssessmentSupplement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This file contains models most directly related to assessments of SLOs, excluding data collection
Copied from previous project

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
