.TH "mysite.core.models.data_models.SLOStatus" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.data_models.SLOStatus
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatus\fP = models\&.CharField(max_length=50, choices=SLO_STATUS_CHOICES)"
.br
.ti -1c
.RI "\fBsloIR\fP = models\&.OneToOneField('\fBSLOInReport\fP',on_delete=models\&.CASCADE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Status of whether the target was met for an SLO

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "mysite\&.core\&.models\&.data_models\&.SLOStatus\&.sloIR = models\&.OneToOneField('\fBSLOInReport\fP',on_delete=models\&.CASCADE)\fC [static]\fP"

.SS "mysite\&.core\&.models\&.data_models\&.SLOStatus\&.status = models\&.CharField(max_length=50, choices=SLO_STATUS_CHOICES)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
