.TH "mysite.core.models.basic_models.NonArchivedManager" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.basic_models.NonArchivedManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Manager\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget_queryset\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Includes only active objects

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def mysite\&.core\&.models\&.basic_models\&.NonArchivedManager\&.get_queryset ( self)"

.PP
.nf
Retrieves only active objects within type

Returns:
    QuerySet : active objects only

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
