.TH "mysite.core.views" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.views
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHome\fP"
.br
.ti -1c
.RI "class \fBReportListView\fP"
.br
.ti -1c
.RI "class \fBUploadReportView\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBupload\fP (request)"
.br
.ti -1c
.RI "def \fBreport_list\fP (request)"
.br
.ti -1c
.RI "def \fBupload_report\fP (request)"
.br
.ti -1c
.RI "def \fBdelete_report\fP (request, pk)"
.br
.ti -1c
.RI "def \fBsearch\fP (request)"
.br
.ti -1c
.RI "def \fBview_report\fP (request)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def mysite\&.core\&.views\&.delete_report ( request,  pk)"

.SS "def mysite\&.core\&.views\&.report_list ( request)"

.SS "def mysite\&.core\&.views\&.search ( request)"

.SS "def mysite\&.core\&.views\&.upload ( request)"

.SS "def mysite\&.core\&.views\&.upload_report ( request)"

.SS "def mysite\&.core\&.views\&.view_report ( request)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
