.TH "mysite.core.models.basic_models" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.basic_models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNonArchivedManager\fP"
.br
.ti -1c
.RI "class \fBUploadReport\fP"
.br
.ti -1c
.RI "class \fBReport\fP"
.br
.ti -1c
.RI "class \fBProfile\fP"
.br
.ti -1c
.RI "class \fBFileModel\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBuser_directory_path\fP (instance, filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Includes most common models used extensively by all users across the site
Copied from previous project with some modifications

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def mysite\&.core\&.models\&.basic_models\&.user_directory_path ( instance,  filename)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
