.TH "mysite.core.models.assessment_models.Assessment" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.assessment_models.Assessment
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBtitle\fP = models\&.CharField(max_length=300)"
.br
.ti -1c
.RI "\fBdomainExamination\fP = models\&.BooleanField(verbose_name='examination domain')"
.br
.ti -1c
.RI "\fBdomainProduct\fP = models\&.BooleanField(verbose_name='product domain')"
.br
.ti -1c
.RI "\fBdomainPerformance\fP = models\&.BooleanField(verbose_name='performance domain')"
.br
.ti -1c
.RI "\fBdirectMeasure\fP = models\&.BooleanField(verbose_name='direct measure')"
.br
.ti -1c
.RI "\fBnumberOfUses\fP = models\&.PositiveIntegerField(default=0, verbose_name='number of uses')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Assessment model collects assessments that are ostensibly the same except for minor changes,
and includes fields which should never change

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def mysite\&.core\&.models\&.assessment_models\&.Assessment\&.__str__ ( self)"

.SH "Member Data Documentation"
.PP 
.SS "mysite\&.core\&.models\&.assessment_models\&.Assessment\&.directMeasure = models\&.BooleanField(verbose_name='direct measure')\fC [static]\fP"

.SS "mysite\&.core\&.models\&.assessment_models\&.Assessment\&.domainExamination = models\&.BooleanField(verbose_name='examination domain')\fC [static]\fP"

.SS "mysite\&.core\&.models\&.assessment_models\&.Assessment\&.domainPerformance = models\&.BooleanField(verbose_name='performance domain')\fC [static]\fP"

.SS "mysite\&.core\&.models\&.assessment_models\&.Assessment\&.domainProduct = models\&.BooleanField(verbose_name='product domain')\fC [static]\fP"

.SS "mysite\&.core\&.models\&.assessment_models\&.Assessment\&.numberOfUses = models\&.PositiveIntegerField(default=0, verbose_name='number of uses')\fC [static]\fP"

.SS "mysite\&.core\&.models\&.assessment_models\&.Assessment\&.title = models\&.CharField(max_length=300)\fC [static]\fP"

.PP
.nf
Assessment model collects assessments that are ostensibly the same except for minor changes,
and includes fields which should never change

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
