.TH "mysite.core.forms.FileFieldForm" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.forms.FileFieldForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits forms\&.Form\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBfile_field\fP = forms\&.FileField(widget=forms\&.ClearableFileInput(attrs={'multiple': True}))"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "mysite\&.core\&.forms\&.FileFieldForm\&.file_field = forms\&.FileField(widget=forms\&.ClearableFileInput(attrs={'multiple': True}))\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
