.TH "mysite.core" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBadmin\fP"
.br
.ti -1c
.RI " \fBapps\fP"
.br
.ti -1c
.RI " \fBchoices\fP"
.br
.ti -1c
.RI " \fBforms\fP"
.br
.ti -1c
.RI " \fBmodels\fP"
.br
.ti -1c
.RI " \fBtests\fP"
.br
.ti -1c
.RI " \fBviews\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
