.TH "mysite.core.forms.UploadFileForm" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.forms.UploadFileForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits forms\&.Form\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBtitle\fP = forms\&.CharField(max_length=50)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "mysite\&.core\&.forms\&.UploadFileForm\&.title = forms\&.CharField(max_length=50)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
