.TH "mysite.core.models.aac_models.Announcement" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite.core.models.aac_models.Announcement
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBtext\fP = models\&.CharField(max_length=2000,blank=True)"
.br
.ti -1c
.RI "\fBexpiration\fP = models\&.DateField()"
.br
.ti -1c
.RI "\fBcreation\fP = models\&.DateTimeField(auto_now_add=True)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Model to hold annnoucements the AAC make

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def mysite\&.core\&.models\&.aac_models\&.Announcement\&.__str__ ( self)"

.SH "Member Data Documentation"
.PP 
.SS "mysite\&.core\&.models\&.aac_models\&.Announcement\&.creation = models\&.DateTimeField(auto_now_add=True)\fC [static]\fP"

.SS "mysite\&.core\&.models\&.aac_models\&.Announcement\&.expiration = models\&.DateField()\fC [static]\fP"

.SS "mysite\&.core\&.models\&.aac_models\&.Announcement\&.text = models\&.CharField(max_length=2000,blank=True)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
