.TH "os_manip" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
os_manip
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsource_dir\fP = input('Enter the source location of the file: example C:/Users/bob/\\n')"
.br
.ti -1c
.RI "\fBsource_fn\fP = input('Enter the name of the file to copy\\n')"
.br
.ti -1c
.RI "\fBdestination_fn\fP = input('Enter the name of the copied file\\n')"
.br
.ti -1c
.RI "\fBzip_dir\fP = input('Enter name of directory to unzip file\\n')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "os_manip\&.destination_fn = input('Enter the name of the copied file\\n')"

.SS "os_manip\&.source_dir = input('Enter the source location of the file: example C:/Users/bob/\\n')"

.SS "os_manip\&.source_fn = input('Enter the name of the file to copy\\n')"

.SS "os_manip\&.zip_dir = input('Enter name of directory to unzip file\\n')"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
