.TH "mysite/core/paser/os_manip.py" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/core/paser/os_manip.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBos_manip\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBos_manip\&.source_dir\fP = input('Enter the source location of the file: example C:/Users/bob/\\n')"
.br
.ti -1c
.RI "\fBos_manip\&.source_fn\fP = input('Enter the name of the file to copy\\n')"
.br
.ti -1c
.RI "\fBos_manip\&.destination_fn\fP = input('Enter the name of the copied file\\n')"
.br
.ti -1c
.RI "\fBos_manip\&.zip_dir\fP = input('Enter name of directory to unzip file\\n')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
