.TH "mysite/core/paser/read_doc_chx.py" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/core/paser/read_doc_chx.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBread_doc_chx\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBread_doc_chx\&.remove_tags\fP (text)"
.br
.RI "Remove < > tags from a string\&. "
.ti -1c
.RI "def \fBread_doc_chx\&.copy_and_unzip\fP (source_dir, source_fn, destination_fn, zip_dir)"
.br
.RI "Copies a file, renames it as a ZIP document, and unzips it\&. "
.ti -1c
.RI "def \fBread_doc_chx\&.find_checkbox_elements\fP (xml_path)"
.br
.RI "Finds all the words directly after the marked checkboxes in the document\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
