.TH "mysite/settings.py" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/settings.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmysite\&.settings\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmysite\&.settings\&.BASE_DIR\fP = os\&.path\&.dirname(os\&.path\&.dirname(os\&.path\&.abspath(__file__)))"
.br
.ti -1c
.RI "string \fBmysite\&.settings\&.SECRET_KEY\fP = '3w5+j6wh0^w9pjv14egctmtb^(7cq#whl%q(_8t*_(q2y^5z@a'"
.br
.ti -1c
.RI "bool \fBmysite\&.settings\&.DEBUG\fP = True"
.br
.ti -1c
.RI "list \fBmysite\&.settings\&.ALLOWED_HOSTS\fP = []"
.br
.ti -1c
.RI "list \fBmysite\&.settings\&.INSTALLED_APPS\fP"
.br
.ti -1c
.RI "string \fBmysite\&.settings\&.CRISPY_TEMPLATE_PACK\fP = 'bootstrap4'"
.br
.ti -1c
.RI "list \fBmysite\&.settings\&.MIDDLEWARE\fP"
.br
.ti -1c
.RI "string \fBmysite\&.settings\&.ROOT_URLCONF\fP = 'mysite\&.urls'"
.br
.ti -1c
.RI "list \fBmysite\&.settings\&.TEMPLATES\fP"
.br
.ti -1c
.RI "string \fBmysite\&.settings\&.WSGI_APPLICATION\fP = '\fBmysite\&.wsgi\&.application\fP'"
.br
.ti -1c
.RI "dictionary \fBmysite\&.settings\&.DATABASES\fP"
.br
.ti -1c
.RI "list \fBmysite\&.settings\&.AUTH_PASSWORD_VALIDATORS\fP"
.br
.ti -1c
.RI "string \fBmysite\&.settings\&.LANGUAGE_CODE\fP = 'en\-us'"
.br
.ti -1c
.RI "string \fBmysite\&.settings\&.TIME_ZONE\fP = 'UTC'"
.br
.ti -1c
.RI "bool \fBmysite\&.settings\&.USE_I18N\fP = True"
.br
.ti -1c
.RI "bool \fBmysite\&.settings\&.USE_L10N\fP = True"
.br
.ti -1c
.RI "bool \fBmysite\&.settings\&.USE_TZ\fP = True"
.br
.ti -1c
.RI "\fBmysite\&.settings\&.STATIC_ROOT\fP = os\&.path\&.join(BASE_DIR, 'staticfiles')"
.br
.ti -1c
.RI "string \fBmysite\&.settings\&.STATIC_URL\fP = '/static/'"
.br
.ti -1c
.RI "list \fBmysite\&.settings\&.STATICFILES_DIRS\fP"
.br
.ti -1c
.RI "\fBmysite\&.settings\&.MEDIA_ROOT\fP = os\&.path\&.join(BASE_DIR, 'media')"
.br
.ti -1c
.RI "string \fBmysite\&.settings\&.MEDIA_URL\fP = '/media/'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
