.TH "mysite/core/views.py" 3 "Thu May 6 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mysite/core/views.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmysite\&.core\&.views\&.Home\fP"
.br
.ti -1c
.RI "class \fBmysite\&.core\&.views\&.ReportListView\fP"
.br
.ti -1c
.RI "class \fBmysite\&.core\&.views\&.UploadReportView\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmysite\&.core\&.views\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmysite\&.core\&.views\&.upload\fP (request)"
.br
.ti -1c
.RI "def \fBmysite\&.core\&.views\&.report_list\fP (request)"
.br
.ti -1c
.RI "def \fBmysite\&.core\&.views\&.upload_report\fP (request)"
.br
.ti -1c
.RI "def \fBmysite\&.core\&.views\&.delete_report\fP (request, pk)"
.br
.ti -1c
.RI "def \fBmysite\&.core\&.views\&.search\fP (request)"
.br
.ti -1c
.RI "def \fBmysite\&.core\&.views\&.view_report\fP (request)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
